import type { Metadata } from "next";

import { Roboto } from "next/font/google"
import { Oswald } from "next/font/google"
import { Kanit } from "next/font/google"
import { Anton } from "next/font/google"
import { Bebas_Neue } from "next/font/google";
import { Teko } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  weight: "400",
  subsets: ["latin"]
})

const kanit = Kanit({
  variable: "--font-kanit",
  weight: "500",
  subsets: ["latin"]
})

const oswald = Oswald({
  variable: "--font-oswald",
  weight: "700",
  subsets: ["latin"]
})
const anton = Anton({
  variable: "--font-anton",
  weight: "400",
  subsets: ["latin"]
})
const bebas = Bebas_Neue({
  variable: "--font-bebas",
  weight: "400",
  subsets: ["latin"]
})
const teko = Teko({
  variable: "--font-teko",
  weight: "400",
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${roboto.variable} ${oswald.variable} ${kanit.variable} ${anton.variable} ${bebas.variable} ${teko.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
